# fly.toml app configuration file generated for product-customizer on 2024-02-08T16:14:59+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'product-customizer'
primary_region = 'sin'

[build]

[env]
  PORT = "8081"
  SHOPIFY_APP_URL = "https://product-customizer.fly.dev"
  SHOPIFY_API_KEY = "9a92ac27062831533623257a086effb5"
  SCOPES = "write_products"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
