# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-customizer"
client_id = "6e4b9214aa959ae61a923162f6e6d8a1"
application_url = "https://bundle-fox-emotions-developments.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bundle-fox-emotions-developments.trycloudflare.com/auth/callback",
  "https://bundle-fox-emotions-developments.trycloudflare.com/auth/shopify/callback",
  "https://bundle-fox-emotions-developments.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sakin-development-store.myshopify.com"
