# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Product Customizer"
client_id = "9a92ac27062831533623257a086effb5"
application_url = "https://honey-xerox-fool-kruger.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://honey-xerox-fool-kruger.trycloudflare.com/auth/callback",
  "https://honey-xerox-fool-kruger.trycloudflare.com/auth/shopify/callback",
  "https://honey-xerox-fool-kruger.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sakin-hossain.myshopify.com"
